### ISSUE TITLE
Aliases and formatting

### ISSUE THREAD

**Issue by Korijn** [ClinicalGraphics/keycmd#23]
In order to enable DRY configuration, it should be possible to create aliases. So that a credential can be exposed under more than 1 name.

I guess that applying effects like b64 should also be configurable per alias to make it truly DRY.

```toml
[keys]
PAT = { credential = "credential-name", username = "your-username" }

[aliases]
PAT_B64 = { key = "PAT", b64 = true }
ALSO_PAT = { key = "PAT" }
ALSO_PAT = { key = "PAT", format = "[username]:[password]", b64 = true }
```
